"""baseline

Revision ID: 2d35b4cb47dc
Revises: 
Create Date: 2026-09-05 07:50:12.199676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2d35b4cb47dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hdrezka_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hdrezka_id')
    )
    op.create_table('meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'ref_id', name='uq_notification')
    )
    op.create_index('notifications_queue', 'notifications', ['next_attempt_at', 'id'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hdrezka_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('year', sa.String(length=16), nullable=True),
    sa.Column('section', sa.String(length=32), nullable=True),
    sa.Column('content_type', sa.String(length=16), nullable=True),
    sa.Column('is_finished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_season', sa.Integer(), nullable=True),
    sa.Column('last_episode', sa.Integer(), nullable=True),
    sa.Column('default_translator', sa.Integer(), nullable=True),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('page_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hdrezka_id')
    )
    op.create_index('pages_franchise', 'pages', ['franchise_id'], unique=False)
    op.create_index('pages_ongoing', 'pages', ['page_refreshed_at'], unique=False, postgresql_where=sa.text('NOT is_finished'))
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'season', 'episode', name='uq_episode')
    )
    op.create_index(op.f('ix_episodes_page_id'), 'episodes', ['page_id'], unique=False)
    op.create_table('schedule',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('aired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'season', 'episode')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('franchise_id', sa.Integer(), nullable=True),
    sa.Column('voice_filter', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'page' AND page_id IS NOT NULL AND franchise_id IS NULL) OR (scope = 'franchise' AND franchise_id IS NOT NULL AND page_id IS NULL)", name='ck_subscription_scope'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('subs_by_franchise', 'subscriptions', ['franchise_id'], unique=False)
    op.create_index('subs_by_page', 'subscriptions', ['page_id'], unique=False)
    op.create_index('subs_user_franchise', 'subscriptions', ['user_id', 'franchise_id'], unique=True, postgresql_where=sa.text('franchise_id IS NOT NULL'))
    op.create_index('subs_user_page', 'subscriptions', ['user_id', 'page_id'], unique=True, postgresql_where=sa.text('page_id IS NOT NULL'))
    op.create_table('voices',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('translator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'translator_id')
    )
    op.create_table('episode_voices',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('translator_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'translator_id')
    )
    op.create_table('voice_checks',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('translator_id', sa.Integer(), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'translator_id')
    )
    op.create_index('voice_checks_due', 'voice_checks', ['next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('voice_checks_due', table_name='voice_checks')
    op.drop_table('voice_checks')
    op.drop_table('episode_voices')
    op.drop_table('voices')
    op.drop_index('subs_user_page', table_name='subscriptions', postgresql_where=sa.text('page_id IS NOT NULL'))
    op.drop_index('subs_user_franchise', table_name='subscriptions', postgresql_where=sa.text('franchise_id IS NOT NULL'))
    op.drop_index('subs_by_page', table_name='subscriptions')
    op.drop_index('subs_by_franchise', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_episodes_page_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('pages_ongoing', table_name='pages', postgresql_where=sa.text('NOT is_finished'))
    op.drop_index('pages_franchise', table_name='pages')
    op.drop_table('pages')
    op.drop_table('users')
    op.drop_index('notifications_queue', table_name='notifications', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('notifications')
    op.drop_table('meta')
    op.drop_table('franchises')
    # ### end Alembic commands ###
